# Generated by Django 5.0.7 on 2024-07-25 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='activos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activos', models.CharField(max_length=40)),
                ('id_activos', models.IntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='cliente',
            new_name='clientes',
        ),
    ]
