# Generated by Django 5.0.7 on 2024-07-30 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_formulario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicios',
            old_name='servicio',
            new_name='servicios',
        ),
    ]
