# Generated by Django 5.0.7 on 2024-07-31 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_servicio_servicios_servicios'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicios',
            old_name='servicios',
            new_name='servicio',
        ),
    ]
