# Generated by Django 5.0.7 on 2024-07-31 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_servicios_servicios_servicio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicios',
            old_name='servicio',
            new_name='servicios',
        ),
    ]
