# Generated by Django 5.0.7 on 2024-07-31 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_servicio_servicios_servicios'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='formulario',
            new_name='f_formulario',
        ),
        migrations.RenameField(
            model_name='f_formulario',
            old_name='servicio',
            new_name='servicios',
        ),
    ]
