# Generated by Django 5.0.7 on 2024-07-31 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_formulario_f_formulario_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='f_formulario',
            new_name='formulario',
        ),
    ]
