# Generated by Django 5.0.7 on 2024-07-31 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_f_formulario_formulario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formulario',
            old_name='servicios',
            new_name='servicio',
        ),
        migrations.RenameField(
            model_name='servicios',
            old_name='servicios',
            new_name='servicio',
        ),
    ]
