# Generated by Django 5.0.7 on 2024-08-02 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_servicios_formulario_servicio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='Mensaje',
            field=models.TextField(default='', max_length=40),
        ),
    ]
