# Generated by Django 5.0.7 on 2024-08-02 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_clientes_mensaje'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=40)),
                ('Apellido', models.CharField(max_length=40)),
                ('Email', models.EmailField(max_length=40)),
                ('Telefono', models.CharField(max_length=40)),
                ('Mensaje', models.TextField(default='', max_length=40)),
            ],
        ),
    ]
