# Generated by Django 5.0.7 on 2024-08-04 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_service'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
    ]
