# Generated by Django 5.0.7 on 2024-08-07 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_delete_service'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactForm',
            new_name='Contacto',
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='Mensaje',
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='Telefono',
        ),
    ]
