# Generated by Django 5.0.7 on 2024-08-08 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_rename_contactform_contacto_remove_clientes_mensaje_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contacto',
            new_name='contactform',
        ),
        migrations.AddField(
            model_name='clientes',
            name='Mensaje',
            field=models.TextField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='clientes',
            name='Telefono',
            field=models.CharField(default='exit', max_length=40),
            preserve_default=False,
        ),
    ]
