# Generated by Django 5.0.7 on 2024-08-08 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_rename_contacto_contactform_clientes_mensaje_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='Mensaje',
            field=models.TextField(default='', max_length=400),
        ),
    ]
